site_name: RTFM
extra_css:
    - css/rtfm.css
extra_javascript:
    - js/rtfm.js
markdown_extensions:
- toc:
    permalink: 'ïƒ'
repo_url: https://github.com/synshop/rtfm
edit_uri: edit/master/docs/

plugins:
    - search
    - tags
#        tags_file: tags.md
    - mermaid2
