name: pulbish site on commits to master
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-mermaid2-plugin
      - run: mkdir local_public
      - run: mkdocs build --clean -d ./local_public/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPOLY_TO_RTFM_SITE}}
          external_repository: synshop/rtfm-generated
          publish_dir: ./local_public/
          user_name: monitoring-synshop-bot
          user_email: monitoring@synshop.org
          publish_branch: master
